[workspace]
git_release_type = "auto"

[[package]]
name = "agent-client-protocol"
git_tag_name = "v{{ version }}"

[[package]]
name = "agent-client-protocol-core"
git_tag_name = "agent-client-protocol-core-v{{ version }}"

[[package]]
name = "agent-client-protocol-derive"
git_tag_name = "agent-client-protocol-derive-v{{ version }}"

[[package]]
name = "agent-client-protocol-rmcp"
git_tag_name = "agent-client-protocol-rmcp-v{{ version }}"

[[package]]
name = "agent-client-protocol-test"
git_tag_name = "agent-client-protocol-test-v{{ version }}"

[[package]]
name = "agent-client-protocol-tokio"
git_tag_name = "agent-client-protocol-tokio-v{{ version }}"

[[package]]
name = "agent-client-protocol-trace-viewer"
git_tag_name = "agent-client-protocol-trace-viewer-v{{ version }}"

[[package]]
name = "agent-client-protocol-yopo"
git_tag_name = "agent-client-protocol-yopo-v{{ version }}"
