name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606
        with:
          toolchain: nightly,stable
          components: rustfmt,clippy

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Check for typos
        uses: crate-ci/typos@02ea592e44b3a53c302f697cddca7641cd051c3d
        with:
          config: ./typos.toml

      - name: Lint
        run: cargo clippy

      - name: Build
        run: cargo build --all-targets --all-features

      - name: Install just
        uses: taiki-e/install-action@a2352fc6ce487f030a3aa709482d57823eadfb37
        with:
          tool: just

      - name: Run tests
        run: just test
